spring.datasource.url=jdbc:${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.application.name=gestao_vagas


security.token.secret=JAVAGAS_@123#
security.token.secret.candidate=JAVAGAS_@123#CANDIDATE




management.endpoints.web.exposure.include=health,info,prometheus
management.metrics.tags.application=${spring.application.name}
management.endpoint.health.probes.enabled=true
management.endpoint.health.show-details=always


server.port=${PORT:8080}